CREATE database elibrary;

CREATE TABLE  E_BOOK(	CALLNO VARCHAR(256), 
	NAME VARCHAR(256), 
	AUTHOR VARCHAR(256), 
	PUBLISHER VARCHAR(256), 
	QUANTITY int, 
	ISSUED int, 
	 CONSTRAINT E_BOOK_PK PRIMARY KEY (CALLNO) 
   );


CREATE TABLE  E_LIBRARIAN 
   (	ID int, 
	NAME VARCHAR(256), 
	PASSWORD VARCHAR(256), 
	EMAIL VARCHAR(256), 
	MOBILE int, 
	 CONSTRAINT E_LIBRARIAN_PK PRIMARY KEY (ID)
   );

CREATE TABLE  E_ISSUEBOOK
   (	CALLNO VARCHAR(256) NOT NULL, 
	STUDENTID VARCHAR(256) NOT NULL, 
	STUDENTNAME VARCHAR(256),
	STUDENTMOBILE int, 
	ISSUEDDATE DATE, 
	RETURNSTATUS VARCHAR(256)
   )


